
name: Build
on:
  push:
    branches:    
      # Push events on master branch
      - master
      # Push events on developer Branch
      - development
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      # Set a placeholder API key for building to prevent crashes
      ALPHA_VANTAGE_API_KEY: "BUILD_API_KEY_FOR_CI"
    
    strategy:
         matrix:
           destination: ['platform=iOS Simulator,name=iPhone 16']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        run: |
          # Ensure API key is available for the build process
          export ALPHA_VANTAGE_API_KEY="BUILD_API_KEY_FOR_CI"
          xcodebuild clean build -project StockWatcher.xcodeproj -scheme StockWatcher -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
