
on:
  push:
    branches:    
      # Push events on master branch
      - master
      # Push events on developer Branch
      - development
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
         matrix:
           destination: ['platform=iOS Simulator,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -workspace StockWatcher.xcworkspace -scheme StockWatcher -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
